apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysql.service.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.service.name }}
  serviceName: {{ .Values.mysql.service.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.service.name }}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: {{ .Values.mysql.service.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.mysql.storage }}
