apiVersion: v1
kind: Service
metadata:
  name: {{ include "gofr-task-api.fullname" . }}-service
spec:
  selector:
    app: {{ include "gofr-task-api.name" . }}
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}
