// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source interface.go -destination=mock_interface.go -package=task
//

// Package task is a generated GoMock package.
package task

import (
	models "ThreeLayerArch/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskService is a mock of TaskService interface.
type MockTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceMockRecorder
	isgomock struct{}
}

// MockTaskServiceMockRecorder is the mock recorder for MockTaskService.
type MockTaskServiceMockRecorder struct {
	mock *MockTaskService
}

// NewMockTaskService creates a new mock instance.
func NewMockTaskService(ctrl *gomock.Controller) *MockTaskService {
	mock := &MockTaskService{ctrl: ctrl}
	mock.recorder = &MockTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskService) EXPECT() *MockTaskServiceMockRecorder {
	return m.recorder
}

// Add_Task mocks base method.
func (m *MockTaskService) Add_Task(task string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add_Task", task)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add_Task indicates an expected call of Add_Task.
func (mr *MockTaskServiceMockRecorder) Add_Task(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add_Task", reflect.TypeOf((*MockTaskService)(nil).Add_Task), task)
}

// Delete_Task mocks base method.
func (m *MockTaskService) Delete_Task(i int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete_Task", i)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete_Task indicates an expected call of Delete_Task.
func (mr *MockTaskServiceMockRecorder) Delete_Task(i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete_Task", reflect.TypeOf((*MockTaskService)(nil).Delete_Task), i)
}

// Get_By_ID mocks base method.
func (m *MockTaskService) Get_By_ID(i int) (models.Tasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get_By_ID", i)
	ret0, _ := ret[0].(models.Tasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get_By_ID indicates an expected call of Get_By_ID.
func (mr *MockTaskServiceMockRecorder) Get_By_ID(i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get_By_ID", reflect.TypeOf((*MockTaskService)(nil).Get_By_ID), i)
}

// Update_Task mocks base method.
func (m *MockTaskService) Update_Task(i int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update_Task", i)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update_Task indicates an expected call of Update_Task.
func (mr *MockTaskServiceMockRecorder) Update_Task(i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update_Task", reflect.TypeOf((*MockTaskService)(nil).Update_Task), i)
}

// View_Task mocks base method.
func (m *MockTaskService) View_Task() ([]models.Tasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "View_Task")
	ret0, _ := ret[0].([]models.Tasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// View_Task indicates an expected call of View_Task.
func (mr *MockTaskServiceMockRecorder) View_Task() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "View_Task", reflect.TypeOf((*MockTaskService)(nil).View_Task))
}
